"""Idempotent product seed (upsert by name). Run via scripts/seed_database.py."""
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.database.models import Product

PRODUCTS = [
    ("Logitech K380 Wireless Keyboard", "Compact multi-device Bluetooth keyboard", "35.00", 12, "Keyboards", True),
    ("Keychron K2 Mechanical Keyboard", "Wireless 75% mechanical keyboard, hot-swappable", "89.00", 5, "Keyboards", True),
    ("Dell KB216 Wired Keyboard", "Full-size wired USB keyboard", "15.00", 40, "Keyboards", True),
    ("Logitech MX Keys Wireless Keyboard", "Backlit wireless keyboard for productivity", "109.00", 0, "Keyboards", True),
    ("Logitech M185 Wireless Mouse", "Compact wireless mouse, 12-month battery", "14.00", 30, "Mice", True),
    ("Logitech MX Master 3S Wireless Mouse", "Ergonomic wireless mouse, silent clicks", "99.00", 7, "Mice", True),
    ("Razer DeathAdder Gaming Mouse", "Wired ergonomic gaming mouse", "49.00", 10, "Mice", True),
    ("Sony WH-CH520 Wireless Headphones", "Bluetooth on-ear headphones, 50h battery", "59.00", 15, "Audio", True),
    ("JBL Tune 510BT Headphones", "Wireless on-ear headphones", "39.00", 20, "Audio", True),
    ("Anker 65W USB-C Charger", "Fast GaN wall charger, 2 ports", "29.00", 25, "Accessories", True),
    ("Samsung 27in Full HD Monitor", "27-inch IPS monitor, 75Hz", "159.00", 6, "Monitors", True),
    ("Legacy PS/2 Keyboard", "Discontinued model", "9.00", 3, "Keyboards", False),
    ("Logitech K120 Wired Keyboard", "Full-size USB office keyboard", "12.00", 35, "Keyboards", True),
    ("Keychron K6 Mechanical Keyboard", "Compact wireless mechanical keyboard", "79.00", 9, "Keyboards", True),
    ("Logitech G502 HERO Gaming Mouse", "Wired gaming mouse with customizable buttons", "45.00", 11, "Mice", True),
    ("Microsoft Bluetooth Mouse", "Compact Bluetooth mouse", "24.00", 18, "Mice", True),
    ("Dell Inspiron 15 Laptop", "15.6-inch laptop for work and study", "649.00", 8, "Laptops", True),
    ("Lenovo IdeaPad Slim 3", "Laptop for everyday work and study", "499.00", 12, "Laptops", True),
    ("HP Pavilion 14 Laptop", "14-inch laptop with SSD storage", "579.00", 6, "Laptops", True),
    ("Dell 24-inch Full HD Monitor", "24-inch Full HD monitor", "139.00", 7, "Monitors", True),
    ("LG 27-inch QHD Monitor", "27-inch QHD productivity monitor", "279.00", 4, "Monitors", True),
    ("Logitech C920 HD Webcam", "1080p webcam for video calls", "69.00", 10, "Webcams", True),
    ("Anker USB-C Hub 7-in-1", "USB-C hub with HDMI and USB ports", "39.00", 14, "Accessories", True),
        ('Anker 65W USB-C Charger', 'Fast USB-C wall charger', '55.10', 174, 'Accessories', True),
    ('USB-C to USB-C Cable 2m', 'Durable braided charging cable', '110.57', 70, 'Accessories', True),
    ('Wireless Charging Pad', 'Qi-compatible wireless charging pad', '51.75', 69, 'Accessories', True),
    ('Laptop Sleeve 15-inch', 'Padded protective laptop sleeve', '29.59', 105, 'Accessories', True),
    ('USB-C Hub 7-in-1', 'Multiport adapter with HDMI and USB ports', '4.87', 149, 'Accessories', True),
    ('Bluetooth Tracker Tag', 'Compact item finder with replaceable battery', '51.84', 159, 'Accessories', True),
    ('Portable Power Bank 20000mAh', 'High-capacity portable battery pack', '32.27', 79, 'Accessories', True),
    ('Phone Tripod Stand', 'Adjustable tabletop phone tripod', '113.97', 178, 'Accessories', True),
    ('Tempered Glass Screen Protector', 'Scratch-resistant screen protector', '42.98', 105, 'Accessories', True),
    ('Universal Travel Adapter', 'Compact international plug adapter', '12.86', 103, 'Accessories', True),
    ('HDMI Cable 2m', 'High-speed HDMI cable for displays', '111.13', 148, 'Accessories', True),
    ('Ethernet Cable 5m', 'Cat6 network cable for wired connections', '10.15', 112, 'Accessories', True),
    ('Wireless Mouse', 'Ergonomic wireless optical mouse', '91.51', 22, 'Accessories', True),
    ('Mechanical Keyboard', 'Compact mechanical keyboard with tactile switches', '52.99', 83, 'Accessories', True),
    ('Webcam 1080p', 'Full HD webcam for calls and streaming', '130.71', 178, 'Accessories', True),
    ('Noise-Isolating Earbuds', 'Wired in-ear earbuds with microphone', '79.68', 177, 'Accessories', True),
    ('Bluetooth Headphones', 'Over-ear wireless headphones', '62.66', 30, 'Accessories', True),
    ('USB Flash Drive 128GB', 'Portable USB storage drive', '75.01', 143, 'Accessories', True),
    ('External SSD 1TB', 'Portable solid-state storage drive', '44.94', 11, 'Accessories', True),
    ('Laptop Cooling Pad', 'USB-powered laptop cooling stand', '81.05', 110, 'Accessories', True),
    ('Classic Cotton T-Shirt', 'Everyday cotton crew-neck T-shirt', '67.26', 130, 'Clothing', True),
    ("Men's Oxford Shirt", 'Button-down cotton-blend Oxford shirt', '68.28', 155, 'Clothing', True),
    ("Women's Linen Blouse", 'Lightweight linen-blend casual blouse', '79.18', 93, 'Clothing', True),
    ('Unisex Zip Hoodie', 'Soft fleece zip-up hoodie', '99.12', 73, 'Clothing', True),
    ('Slim-Fit Jeans', 'Stretch denim jeans with slim fit', '10.96', 12, 'Clothing', True),
    ('Chino Trousers', 'Smart-casual cotton-blend trousers', '22.42', 167, 'Clothing', True),
    ('Running Shorts', 'Lightweight moisture-wicking sports shorts', '82.86', 5, 'Clothing', True),
    ('Puffer Jacket', 'Insulated jacket for cold weather', '103.63', 151, 'Clothing', True),
    ('Rain Jacket', 'Water-resistant hooded rain jacket', '65.52', 33, 'Clothing', True),
    ('Wool Blend Scarf', 'Soft warm scarf for winter', '65.91', 137, 'Clothing', True),
    ('Knit Beanie', 'Ribbed knit beanie hat', '30.64', 106, 'Clothing', True),
    ('Leather Belt', 'Classic adjustable everyday belt', '68.06', 41, 'Clothing', True),
    ('Canvas Sneakers', 'Low-top casual canvas sneakers', '33.61', 14, 'Clothing', False),
    ('Running Shoes', 'Cushioned athletic running shoes', '7.07', 125, 'Clothing', True),
    ('Crew Socks 5-Pack', 'Comfortable cotton-blend crew socks', '117.80', 107, 'Clothing', True),
    ('Cotton Pajama Set', 'Breathable two-piece sleepwear set', '6.15', 41, 'Clothing', True),
    ('Sports Leggings', 'Stretch leggings for training and yoga', '5.36', 151, 'Clothing', True),
    ('Baseball Cap', 'Adjustable cotton baseball cap', '87.75', 110, 'Clothing', True),
    ('Leather Wallet', 'Slim wallet with multiple card slots', '9.43', 159, 'Clothing', True),
    ('Reusable Tote Bag', 'Foldable shopping tote made from sturdy fabric', '59.93', 155, 'Clothing', True),
    ('Ceramic Dinner Plate Set', 'Set of four glazed ceramic dinner plates', '70.23', 134, 'Home', True),
    ('Stainless Steel Water Bottle', 'Insulated reusable bottle, 750 ml', '173.54', 41, 'Home', True),
    ('Glass Food Storage Set', 'Set of three lidded food storage containers', '37.75', 129, 'Home', True),
    ('Nonstick Frying Pan 28cm', 'Nonstick skillet for everyday cooking', '131.78', 108, 'Home', True),
    ('Stainless Steel Saucepan', 'Medium saucepan with tempered glass lid', '176.45', 152, 'Home', True),
    ('Bamboo Cutting Board', 'Durable bamboo board for food preparation', '174.69', 107, 'Home', False),
    ('Chef Knife 20cm', 'Stainless steel kitchen chef knife', '24.50', 63, 'Home', True),
    ('Electric Kettle 1.7L', 'Fast-boil kettle with automatic shutoff', '45.06', 175, 'Home', True),
    ('French Press Coffee Maker', 'Glass coffee press for brewed coffee', '101.93', 139, 'Home', True),
    ('Digital Kitchen Scale', 'Compact scale with gram and ounce readings', '69.62', 7, 'Home', True),
    ('Cotton Bath Towel', 'Absorbent full-size cotton bath towel', '67.63', 66, 'Home', True),
    ('Microfiber Cleaning Cloths 6-Pack', 'Reusable cloths for household cleaning', '80.79', 16, 'Home', True),
    ('LED Desk Lamp', 'Adjustable desk lamp with dimmable LED', '58.69', 157, 'Home', True),
    ('Queen Fitted Sheet', 'Soft fitted sheet for a queen mattress', '62.99', 126, 'Home', True),
    ('Memory Foam Pillow', 'Supportive pillow with removable cover', '176.37', 68, 'Home', True),
    ('Laundry Basket', 'Ventilated hamper with carry handles', '111.51', 110, 'Home', True),
    ('Vacuum Storage Bags 5-Pack', 'Space-saving bags for seasonal clothing', '51.20', 43, 'Home', True),
    ('Wall Clock 30cm', 'Quiet quartz wall clock for home or office', '68.89', 122, 'Home', True),
    ('Scented Candle', 'Jar candle with a warm vanilla fragrance', '36.80', 5, 'Home', True),
    ('Indoor Plant Pot 20cm', 'Minimal ceramic planter with drainage hole', '110.18', 145, 'Home', True),
    ('A4 Copy Paper 500 Sheets', 'Standard white paper for printing and copying', '160.14', 176, 'Office', True),
    ('Ballpoint Pens 10-Pack', 'Smooth-writing blue ink ballpoint pens', '202.59', 120, 'Office', True),
    ('Hardcover Notebook A5', 'Ruled notebook with durable hardcover', '26.54', 15, 'Office', True),
    ('Sticky Notes 12-Pack', 'Assorted-color adhesive memo notes', '21.33', 159, 'Office', True),
    ('Permanent Markers 4-Pack', 'Water-resistant black permanent markers', '3.78', 130, 'Office', True),
    ('Highlighter Set 6-Pack', 'Bright chisel-tip highlighters in assorted colors', '147.14', 93, 'Office', True),
    ('Desktop File Organizer', 'Multi-compartment organizer for documents', '21.03', 117, 'Office', True),
    ('Lever Arch File', 'Durable file folder for A4 documents', '35.20', 118, 'Office', True),
    ('Stapler with Staples', 'Desktop stapler supplied with staples', '60.49', 61, 'Office', True),
    ('Scissors 8-inch', 'General-purpose stainless steel scissors', '162.58', 151, 'Office', True),
    ('Packing Tape 6-Pack', 'Clear adhesive tape rolls for packing', '76.94', 142, 'Office', False),
    ('Desk Mat', 'Protective desk mat with smooth work surface', '25.39', 65, 'Office', True),
    ('Whiteboard 60x90cm', 'Wall-mounted dry-erase board', '116.97', 80, 'Office', True),
    ('Whiteboard Marker Set', 'Low-odor dry-erase markers in four colors', '44.41', 49, 'Office', True),
    ('Scientific Calculator', 'Multi-function calculator for study and work', '180.44', 167, 'Office', True),
    ('Ergonomic Office Chair', 'Adjustable office chair with lumbar support', '47.02', 148, 'Office', True),
    ('Monitor Stand', 'Raised monitor platform with storage space', '74.03', 58, 'Office', True),
    ('Weekly Planner', 'Undated weekly planner for task organization', '60.40', 143, 'Office', True),
    ('Document Wallet', 'Expandable wallet for loose papers', '193.88', 98, 'Office', True),
    ('Printer Ink Cartridge', 'Replacement ink cartridge for compatible printers', '189.80', 9, 'Office', True),
    ('Yoga Mat 6mm', 'Non-slip exercise mat for yoga and stretching', '8.52', 140, 'Sports', False),
    ('Resistance Bands Set', 'Set of five resistance bands for workouts', '152.33', 133, 'Sports', True),
    ('Adjustable Dumbbell 10kg', 'Single adjustable dumbbell for strength training', '90.12', 73, 'Sports', True),
    ('Stainless Steel Shaker Bottle', 'Leak-resistant shaker for protein drinks', '5.33', 57, 'Sports', True),
    ('Jump Rope', 'Adjustable skipping rope with comfortable handles', '80.55', 126, 'Sports', True),
    ('Foam Roller', 'Textured roller for post-workout muscle massage', '30.73', 120, 'Sports', True),
    ('Basketball Size 7', 'Durable indoor and outdoor basketball', '126.90', 105, 'Sports', True),
    ('Football Size 5', 'Training football with durable outer surface', '98.69', 117, 'Sports', True),
    ('Badminton Racket', 'Lightweight racket for recreational badminton', '66.03', 123, 'Sports', True),
    ('Tennis Balls 3-Pack', 'Pressurized tennis balls for practice and play', '129.96', 86, 'Sports', True),
    ('Swimming Goggles', 'Adjustable anti-fog goggles for swimming', '40.95', 131, 'Sports', True),
    ('Cycling Water Bottle', 'Squeeze bottle designed for bicycle cages', '128.64', 180, 'Sports', True),
    ('Bike Repair Kit', 'Compact tire patch and repair tool kit', '79.78', 80, 'Sports', True),
    ('Camping Headlamp', 'LED headlamp with adjustable brightness', '4.24', 38, 'Sports', True),
    ('Insulated Camping Mug', 'Double-wall mug for outdoor drinks', '136.49', 124, 'Sports', True),
    ('Hiking Daypack 20L', 'Lightweight backpack for day hikes', '51.01', 119, 'Sports', True),
    ('Sleeping Bag', 'Three-season sleeping bag for camping', '110.57', 69, 'Sports', True),
    ('Portable Camping Lantern', 'Rechargeable lantern for campsite lighting', '150.72', 151, 'Sports', True),
    ('Knee Support Sleeve', 'Stretch support sleeve for sports activities', '62.98', 50, 'Sports', True),
    ('Sports Duffel Bag', 'Roomy gym bag with separate shoe compartment', '44.37', 10, 'Sports', False),
    ('Gentle Facial Cleanser', 'Daily face cleanser for removing dirt and oil', '53.91', 98, 'Beauty', True),
    ('Moisturizing Face Cream', 'Lightweight daily facial moisturizer', '54.65', 46, 'Beauty', True),
    ('SPF 50 Sunscreen', 'Broad-spectrum sunscreen for everyday use', '17.96', 17, 'Beauty', True),
    ('Lip Balm 3-Pack', 'Moisturizing lip balm in assorted flavors', '63.46', 119, 'Beauty', True),
    ('Shampoo 400ml', 'Daily cleansing shampoo for hair', '69.76', 139, 'Beauty', True),
    ('Conditioner 400ml', 'Hair conditioner for softness and manageability', '81.48', 63, 'Beauty', True),
    ('Body Lotion 250ml', 'Hydrating lotion for everyday body care', '13.39', 87, 'Beauty', True),
    ('Hand Cream', 'Travel-size cream for dry hands', '41.11', 8, 'Beauty', True),
    ('Facial Sheet Masks 5-Pack', 'Disposable hydrating sheet masks', '84.91', 5, 'Beauty', True),
    ('Makeup Brush Set', 'Set of cosmetic brushes for face and eyes', '24.13', 38, 'Beauty', True),
    ('Nail Clipper Set', 'Stainless steel grooming tools for nails', '77.38', 166, 'Beauty', True),
    ('Hair Dryer 1800W', 'Hair dryer with two heat settings', '15.36', 28, 'Beauty', True),
    ('Ceramic Hair Straightener', 'Heated styling tool with ceramic plates', '27.93', 150, 'Beauty', True),
    ('Electric Toothbrush', 'Rechargeable toothbrush with replacement head', '5.19', 105, 'Beauty', True),
    ('Floss Picks 50-Pack', 'Disposable dental floss picks', '58.20', 123, 'Beauty', True),
    ('Cotton Makeup Pads 100-Pack', 'Soft cotton pads for cosmetic use', '36.83', 69, 'Beauty', True),
    ('Perfume Atomizer 10ml', 'Refillable travel spray bottle', '83.87', 40, 'Beauty', True),
    ('Cosmetic Organizer', 'Compartment organizer for beauty products', '47.49', 131, 'Beauty', True),
    ('Bath Bomb Gift Set', 'Set of scented bath fizzers', '73.59', 157, 'Beauty', True),
    ('Wide-Tooth Comb', 'Gentle comb for detangling wet or dry hair', '14.25', 34, 'Beauty', True),
    ('Wooden Building Blocks', 'Colorful wooden blocks for creative play', '82.17', 150, 'Toys', True),
    ('Jigsaw Puzzle 1000 Pieces', 'Illustrated puzzle for adults and older children', '103.80', 60, 'Toys', True),
    ('Remote Control Car', 'Rechargeable toy car with handheld controller', '58.99', 103, 'Toys', True),
    ('Plush Teddy Bear', 'Soft stuffed teddy bear for gifting', '64.36', 77, 'Toys', True),
    ('Watercolor Paint Set', 'Washable watercolor paints with brush', '102.91', 54, 'Toys', True),
    ('Kids Drawing Pad', 'Blank drawing pad for art activities', '34.80', 8, 'Toys', False),
    ('Magnetic Building Tiles', 'Colorful magnetic construction tiles', '16.43', 65, 'Toys', True),
    ('Board Game Classic Edition', 'Family strategy board game', '101.55', 79, 'Toys', True),
    ('Foam Dart Blaster', 'Toy blaster with soft foam darts', '54.97', 96, 'Toys', True),
    ('Kids Science Experiment Kit', 'Beginner-friendly hands-on science kit', '81.51', 47, 'Toys', True),
    ('Dinosaur Figure Set', 'Set of assorted realistic dinosaur figures', '50.18', 156, 'Toys', True),
    ('Toy Train Set', 'Battery-powered train with track pieces', '62.54', 179, 'Toys', True),
    ('Play Dough 12-Pack', 'Modeling dough in assorted colors', '81.54', 36, 'Toys', True),
    ('Kids Gardening Set', 'Small gardening tools for young learners', '109.72', 117, 'Toys', True),
    ('Card Game Travel Edition', 'Compact card game for family trips', '15.11', 90, 'Toys', True),
    ('Stuffed Rabbit Plush', 'Soft rabbit plush toy with embroidered details', '71.48', 12, 'Toys', True),
    ('Kids Scooter Helmet', 'Adjustable protective helmet for cycling and scooting', '99.69', 79, 'Toys', False),
    ('Bubble Machine', 'Battery-operated bubble maker for outdoor play', '72.16', 9, 'Toys', True),
    ('Wooden Shape Sorter', 'Early-learning toy for matching shapes', '6.06', 94, 'Toys', True),
    ('Mini Table Tennis Set', 'Compact paddle and ball set for casual play', '12.98', 72, 'Toys', True),
    ('Basmati Rice 5kg', 'Long-grain aromatic rice for everyday meals', '16.25', 24, 'Grocery', True),
    ('Whole Wheat Flour 5kg', 'Whole wheat flour for breads and flatbreads', '11.48', 94, 'Grocery', True),
    ('Brown Lentils 1kg', 'Dried brown lentils for soups and curries', '28.87', 42, 'Grocery', True),
    ('Chickpeas 1kg', 'Dried chickpeas for home cooking', '13.15', 28, 'Grocery', True),
    ('Rolled Oats 1kg', 'Whole-grain oats for breakfast and baking', '40.65', 79, 'Grocery', True),
    ('Pasta 500g', 'Durum wheat pasta for quick meals', '26.33', 63, 'Grocery', True),
    ('Tomato Passata 700g', 'Smooth tomato puree for sauces', '25.54', 70, 'Grocery', True),
    ('Olive Oil 500ml', 'Extra virgin olive oil for cooking and dressings', '17.36', 176, 'Grocery', True),
    ('Peanut Butter 340g', 'Creamy peanut spread for snacks and sandwiches', '14.29', 92, 'Grocery', True),
    ('Honey 350g', 'Pure honey for drinks and breakfast', '9.69', 54, 'Grocery', True),
    ('Black Tea 250g', 'Loose black tea for daily brewing', '1.59', 53, 'Grocery', True),
    ('Ground Coffee 250g', 'Medium-roast ground coffee for home brewing', '39.43', 110, 'Grocery', True),
    ('Green Tea 100 Bags', 'Green tea bags for convenient brewing', '28.66', 147, 'Grocery', True),
    ('Coconut Milk 400ml', 'Coconut milk for curries and desserts', '14.50', 50, 'Grocery', True),
    ('Corn Flakes 500g', 'Crunchy corn cereal for breakfast', '24.76', 94, 'Grocery', True),
    ('Dark Chocolate 100g', 'Dark chocolate bar for a sweet treat', '7.48', 48, 'Grocery', True),
    ('Mixed Nuts 500g', 'Roasted mixed nuts for snacking', '25.67', 142, 'Grocery', True),
    ('Dried Dates 500g', 'Naturally sweet dried dates', '15.94', 25, 'Grocery', True),
    ('Sea Salt 500g', 'Fine sea salt for seasoning food', '13.51', 78, 'Grocery', True),
    ('Apple Cider Vinegar 500ml', 'Vinegar for dressings and cooking', '6.98', 140, 'Grocery', False),
    ('Writing Desk 120cm', 'Compact desk with a spacious work surface', '111.30', 131, 'Furniture', True),
    ('Bookshelf 5-Tier', 'Freestanding shelf for books and storage', '135.62', 179, 'Furniture', True),
    ('Bedside Table', 'Small side table with drawer and lower shelf', '267.45', 137, 'Furniture', True),
    ('Coffee Table', 'Living room table with sturdy legs', '219.28', 114, 'Furniture', True),
    ('Dining Chair', 'Padded dining chair with solid frame', '345.61', 146, 'Furniture', True),
    ('Folding Study Table', 'Space-saving foldable table for study or work', '372.65', 43, 'Furniture', True),
    ('Shoe Rack 4-Tier', 'Entryway rack for organizing footwear', '370.69', 164, 'Furniture', True),
    ('Storage Ottoman', 'Padded ottoman with hidden storage compartment', '341.41', 105, 'Furniture', True),
    ('Bar Stool', 'Counter-height stool with footrest', '29.70', 127, 'Furniture', True),
    ('TV Stand 120cm', 'Media console with shelves for electronics', '179.47', 17, 'Furniture', True),
    ('Wardrobe Organizer Set', 'Fabric organizers for clothing and accessories', '206.11', 107, 'Furniture', False),
    ('Drawer Storage Unit', 'Plastic drawer unit for household storage', '328.01', 71, 'Furniture', True),
    ('Adjustable Laptop Table', 'Height-adjustable table for laptop use', '94.04', 95, 'Furniture', True),
    ('Floor Cushion', 'Large soft cushion for relaxed seating', '276.44', 80, 'Furniture', True),
    ('Wall-Mounted Floating Shelf', 'Minimal shelf for books and decorations', '343.69', 134, 'Furniture', True),
    ('Coat Rack', 'Standing rack with multiple hanging hooks', '240.92', 165, 'Furniture', True),
    ('Garden Bench', 'Outdoor bench with weather-resistant finish', '257.90', 149, 'Furniture', True),
    ('Folding Camping Chair', 'Portable chair with cup holder', '184.36', 41, 'Furniture', True),
    ('Laundry Drying Rack', 'Foldable rack for air-drying clothes', '298.97', 99, 'Furniture', True),
    ('Full-Length Mirror', 'Standing mirror for bedroom or dressing area', '19.94', 76, 'Furniture', True),
    ('Dry Dog Food 3kg', 'Complete dry food for adult dogs', '66.30', 103, 'Pet Supplies', False),
    ('Cat Food 2kg', 'Dry cat food for everyday feeding', '8.34', 76, 'Pet Supplies', True),
    ('Stainless Pet Bowl', 'Non-slip food and water bowl for pets', '66.27', 144, 'Pet Supplies', True),
    ('Pet Grooming Brush', 'Brush for removing loose fur and tangles', '36.29', 71, 'Pet Supplies', True),
    ('Adjustable Dog Leash', 'Durable leash with comfortable grip', '75.72', 40, 'Pet Supplies', False),
    ('Reflective Dog Collar', 'Adjustable collar with reflective stitching', '33.19', 64, 'Pet Supplies', False),
    ('Cat Litter 10L', 'Absorbent litter for indoor cat trays', '70.26', 109, 'Pet Supplies', True),
    ('Covered Cat Litter Tray', 'Covered litter box with removable top', '80.17', 110, 'Pet Supplies', True),
    ('Pet Travel Carrier', 'Ventilated carrier for small pets', '22.35', 27, 'Pet Supplies', True),
    ('Plush Dog Toy', 'Soft toy for supervised play', '48.19', 11, 'Pet Supplies', True),
    ('Cat Scratching Post', 'Scratch post with stable base', '21.07', 33, 'Pet Supplies', False),
    ('Pet Nail Clippers', 'Safety nail clippers for grooming', '72.82', 170, 'Pet Supplies', True),
    ('Aquarium Filter', 'Compact filter for small home aquariums', '36.61', 58, 'Pet Supplies', True),
    ('Fish Flakes 100g', 'Daily fish food flakes for freshwater fish', '40.58', 140, 'Pet Supplies', True),
    ('Bird Seed Mix 1kg', 'Seed blend for common pet birds', '53.00', 93, 'Pet Supplies', True),
    ('Small Animal Water Bottle', 'Drip-resistant water bottle for cage use', '68.18', 122, 'Pet Supplies', True),
    ('Pet Waste Bags 120-Pack', 'Leak-resistant bags for dog walks', '64.87', 61, 'Pet Supplies', True),
    ('Pet Shampoo 250ml', 'Gentle cleansing shampoo for pets', '47.36', 73, 'Pet Supplies', True),
    ('Dog Training Clicker', 'Handheld clicker for reward-based training', '63.13', 91, 'Pet Supplies', True),
    ('Pet Cooling Mat', 'Cooling surface for warm-weather comfort', '70.89', 28, 'Pet Supplies', True),
    ('Car Phone Mount', 'Adjustable dashboard phone holder', '102.66', 95, 'Automotive', True),
    ('USB Car Charger Dual Port', 'Dual-port charger for vehicle power sockets', '13.86', 98, 'Automotive', True),
    ('Microfiber Car Towels 6-Pack', 'Soft towels for vehicle cleaning', '99.36', 41, 'Automotive', True),
    ('Portable Tire Inflator', 'Compact electric inflator with pressure gauge', '102.19', 112, 'Automotive', True),
    ('Jump Starter 1000A', 'Portable battery booster for compatible vehicles', '233.04', 38, 'Automotive', True),
    ('Windshield Sun Shade', 'Foldable shade to reduce cabin heat', '68.55', 68, 'Automotive', True),
    ('Car Seat Organizer', 'Storage organizer for vehicle seatback', '50.94', 132, 'Automotive', True),
    ('Rubber Floor Mats Set', 'All-weather floor mats for compatible vehicles', '125.53', 177, 'Automotive', True),
    ('Emergency Roadside Kit', 'Basic roadside safety and repair supplies', '207.15', 154, 'Automotive', True),
    ('Car Wash Shampoo 1L', 'Concentrated shampoo for exterior car washing', '18.07', 7, 'Automotive', True),
    ('Tire Pressure Gauge', 'Handheld gauge for checking tire pressure', '83.08', 52, 'Automotive', True),
    ('LED Flashlight', 'Rechargeable flashlight for vehicle emergencies', '118.83', 68, 'Automotive', True),
    ('Trunk Storage Organizer', 'Foldable organizer for cargo storage', '223.24', 175, 'Automotive', True),
    ('Portable Vacuum Cleaner', 'Compact vacuum for vehicle interiors', '8.97', 134, 'Automotive', True),
    ('Ice Scraper', 'Handheld scraper for removing frost from glass', '219.16', 149, 'Automotive', True),
    ('Motorcycle Phone Holder', 'Handlebar mount for compatible smartphones', '234.02', 43, 'Automotive', True),
    ('Car Air Freshener 3-Pack', 'Vent clip fresheners in assorted scents', '136.40', 85, 'Automotive', False),
    ('Reflective Safety Vest', 'High-visibility vest for roadside use', '69.79', 144, 'Automotive', True),
    ('Seat Belt Cushion Pair', 'Soft shoulder pads for seat belt comfort', '21.86', 165, 'Automotive', True),
    ('Motor Oil 1L', 'Engine oil for vehicles requiring the specified grade', '220.43', 26, 'Automotive', True),
    ('Watercolor Sketchbook A4', 'Heavyweight paper sketchbook for wet media', '64.51', 119, 'Stationery', True),
    ('Graphite Pencil Set 12-Pack', 'Drawing pencils in assorted graphite grades', '28.68', 57, 'Stationery', True),
    ('Acrylic Paint Set 12 Colors', 'Acrylic paints for craft and art projects', '59.83', 157, 'Stationery', True),
    ('Paintbrush Set 10-Pack', 'Assorted brushes for painting and crafts', '12.61', 124, 'Stationery', True),
    ('Craft Scoring Tool', 'Hand tool for creasing paper and cardstock', '17.61', 21, 'Stationery', True),
    ('Colored Pencils 24-Pack', 'Color pencils for drawing and coloring', '62.53', 19, 'Stationery', True),
    ('Calligraphy Pen Set', 'Pen set for lettering and decorative writing', '68.82', 59, 'Stationery', True),
    ('Origami Paper 100 Sheets', 'Colorful square paper for folding crafts', '56.38', 136, 'Stationery', True),
    ('Glue Stick 3-Pack', 'Washable glue sticks for paper projects', '59.10', 174, 'Stationery', False),
    ('Craft Storage Box', 'Compartment box for small art supplies', '15.49', 75, 'Stationery', False),
    ('Bullet Journal A5', 'Dotted journal for planning and notes', '54.04', 17, 'Stationery', True),
    ('Index Cards 100-Pack', 'Ruled cards for revision and study notes', '67.77', 140, 'Stationery', True),
    ('Envelope Pack 50', 'White envelopes for letters and documents', '2.93', 78, 'Stationery', True),
    ('Correction Tape 2-Pack', 'Dry correction tape for paper documents', '46.98', 156, 'Stationery', True),
    ('Paper Clips 200-Pack', 'Metal clips for holding papers together', '42.49', 5, 'Stationery', True),
    ('Binder Clips Assorted Set', 'Reusable clips in assorted sizes', '64.66', 19, 'Stationery', True),
    ('Desk Calendar', 'Monthly desktop calendar for date planning', '32.79', 44, 'Stationery', True),
    ('Sketching Charcoal Set', 'Charcoal sticks and pencils for drawing', '41.03', 130, 'Stationery', True),
    ('Poster Board 10-Pack', 'Sheets of poster board for presentations', '11.87', 88, 'Stationery', True),
    ('Label Stickers 500-Pack', 'Adhesive labels for organizing and packaging', '73.76', 43, 'Stationery', True),
    ('Compact USB-C Charger', 'Practical accessory for everyday use with durable materials', '74.09', 41, 'Accessories', True),
    ('Compact Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '12.12', 42, 'Accessories', True),
    ('Compact Wireless Mouse', 'Practical accessory for everyday use with durable materials', '27.90', 177, 'Accessories', True),
    ('Compact Laptop Stand', 'Practical accessory for everyday use with durable materials', '17.56', 155, 'Accessories', True),
    ('Compact Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '44.62', 173, 'Accessories', True),
    ('Compact Power Bank', 'Practical accessory for everyday use with durable materials', '30.26', 78, 'Accessories', True),
    ('Compact Webcam', 'Practical accessory for everyday use with durable materials', '96.13', 73, 'Accessories', True),
    ('Compact USB-C Hub', 'Practical accessory for everyday use with durable materials', '28.44', 84, 'Accessories', True),
    ('Compact Phone Stand', 'Practical accessory for everyday use with durable materials', '108.11', 160, 'Accessories', True),
    ('Compact External SSD', 'Practical accessory for everyday use with durable materials', '125.69', 144, 'Accessories', True),
    ('Premium USB-C Charger', 'Practical accessory for everyday use with durable materials', '127.82', 91, 'Accessories', True),
    ('Premium Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '53.34', 167, 'Accessories', True),
    ('Premium Wireless Mouse', 'Practical accessory for everyday use with durable materials', '34.70', 28, 'Accessories', False),
    ('Premium Laptop Stand', 'Practical accessory for everyday use with durable materials', '28.82', 158, 'Accessories', True),
    ('Premium Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '82.89', 5, 'Accessories', True),
    ('Premium Power Bank', 'Practical accessory for everyday use with durable materials', '125.50', 131, 'Accessories', True),
    ('Premium Webcam', 'Practical accessory for everyday use with durable materials', '110.21', 47, 'Accessories', True),
    ('Premium USB-C Hub', 'Practical accessory for everyday use with durable materials', '13.27', 63, 'Accessories', True),
    ('Premium Phone Stand', 'Practical accessory for everyday use with durable materials', '116.95', 163, 'Accessories', True),
    ('Premium External SSD', 'Practical accessory for everyday use with durable materials', '60.79', 169, 'Accessories', True),
    ('Travel USB-C Charger', 'Practical accessory for everyday use with durable materials', '41.09', 169, 'Accessories', True),
    ('Travel Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '20.85', 20, 'Accessories', True),
    ('Travel Wireless Mouse', 'Practical accessory for everyday use with durable materials', '145.63', 23, 'Accessories', True),
    ('Travel Laptop Stand', 'Practical accessory for everyday use with durable materials', '66.65', 162, 'Accessories', True),
    ('Travel Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '144.67', 17, 'Accessories', True),
    ('Travel Power Bank', 'Practical accessory for everyday use with durable materials', '78.69', 152, 'Accessories', True),
    ('Travel Webcam', 'Practical accessory for everyday use with durable materials', '71.81', 83, 'Accessories', True),
    ('Travel USB-C Hub', 'Practical accessory for everyday use with durable materials', '93.09', 11, 'Accessories', True),
    ('Travel Phone Stand', 'Practical accessory for everyday use with durable materials', '65.35', 41, 'Accessories', True),
    ('Travel External SSD', 'Practical accessory for everyday use with durable materials', '126.76', 176, 'Accessories', True),
    ('Aluminum USB-C Charger', 'Practical accessory for everyday use with durable materials', '67.82', 91, 'Accessories', True),
    ('Aluminum Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '12.97', 21, 'Accessories', True),
    ('Aluminum Wireless Mouse', 'Practical accessory for everyday use with durable materials', '131.23', 65, 'Accessories', True),
    ('Aluminum Laptop Stand', 'Practical accessory for everyday use with durable materials', '133.34', 100, 'Accessories', True),
    ('Aluminum Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '18.02', 24, 'Accessories', True),
    ('Aluminum Power Bank', 'Practical accessory for everyday use with durable materials', '135.60', 179, 'Accessories', True),
    ('Aluminum Webcam', 'Practical accessory for everyday use with durable materials', '93.87', 68, 'Accessories', True),
    ('Aluminum USB-C Hub', 'Practical accessory for everyday use with durable materials', '70.06', 15, 'Accessories', True),
    ('Aluminum Phone Stand', 'Practical accessory for everyday use with durable materials', '83.09', 67, 'Accessories', True),
    ('Aluminum External SSD', 'Practical accessory for everyday use with durable materials', '148.73', 86, 'Accessories', True),
    ('Fast-Charging USB-C Charger', 'Practical accessory for everyday use with durable materials', '133.58', 115, 'Accessories', True),
    ('Fast-Charging Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '29.63', 15, 'Accessories', True),
    ('Fast-Charging Wireless Mouse', 'Practical accessory for everyday use with durable materials', '52.33', 66, 'Accessories', True),
    ('Fast-Charging Laptop Stand', 'Practical accessory for everyday use with durable materials', '11.61', 73, 'Accessories', True),
    ('Fast-Charging Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '131.37', 53, 'Accessories', False),
    ('Fast-Charging Power Bank', 'Practical accessory for everyday use with durable materials', '34.72', 127, 'Accessories', True),
    ('Fast-Charging Webcam', 'Practical accessory for everyday use with durable materials', '5.87', 39, 'Accessories', True),
    ('Fast-Charging USB-C Hub', 'Practical accessory for everyday use with durable materials', '74.47', 142, 'Accessories', True),
    ('Fast-Charging Phone Stand', 'Practical accessory for everyday use with durable materials', '81.35', 31, 'Accessories', False),
    ('Fast-Charging External SSD', 'Practical accessory for everyday use with durable materials', '66.15', 138, 'Accessories', True),
    ('Foldable USB-C Charger', 'Practical accessory for everyday use with durable materials', '87.30', 171, 'Accessories', True),
    ('Foldable Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '136.72', 152, 'Accessories', True),
    ('Foldable Wireless Mouse', 'Practical accessory for everyday use with durable materials', '92.91', 121, 'Accessories', True),
    ('Foldable Laptop Stand', 'Practical accessory for everyday use with durable materials', '62.88', 63, 'Accessories', False),
    ('Foldable Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '39.81', 52, 'Accessories', True),
    ('Foldable Power Bank', 'Practical accessory for everyday use with durable materials', '17.19', 7, 'Accessories', True),
    ('Foldable Webcam', 'Practical accessory for everyday use with durable materials', '99.81', 24, 'Accessories', False),
    ('Foldable USB-C Hub', 'Practical accessory for everyday use with durable materials', '25.89', 81, 'Accessories', True),
    ('Foldable Phone Stand', 'Practical accessory for everyday use with durable materials', '19.04', 134, 'Accessories', True),
    ('Foldable External SSD', 'Practical accessory for everyday use with durable materials', '128.07', 74, 'Accessories', True),
    ('Portable USB-C Charger', 'Practical accessory for everyday use with durable materials', '70.15', 119, 'Accessories', True),
    ('Portable Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '5.31', 73, 'Accessories', True),
    ('Portable Wireless Mouse', 'Practical accessory for everyday use with durable materials', '139.38', 122, 'Accessories', True),
    ('Portable Laptop Stand', 'Practical accessory for everyday use with durable materials', '14.34', 101, 'Accessories', True),
    ('Portable Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '85.60', 86, 'Accessories', True),
    ('Portable Power Bank', 'Practical accessory for everyday use with durable materials', '139.44', 92, 'Accessories', True),
    ('Portable Webcam', 'Practical accessory for everyday use with durable materials', '15.68', 146, 'Accessories', True),
    ('Portable USB-C Hub', 'Practical accessory for everyday use with durable materials', '9.43', 159, 'Accessories', True),
    ('Portable Phone Stand', 'Practical accessory for everyday use with durable materials', '72.66', 104, 'Accessories', True),
    ('Portable External SSD', 'Practical accessory for everyday use with durable materials', '18.83', 94, 'Accessories', True),
    ('Slim USB-C Charger', 'Practical accessory for everyday use with durable materials', '35.22', 138, 'Accessories', True),
    ('Slim Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '38.41', 135, 'Accessories', True),
    ('Slim Wireless Mouse', 'Practical accessory for everyday use with durable materials', '105.72', 120, 'Accessories', True),
    ('Slim Laptop Stand', 'Practical accessory for everyday use with durable materials', '140.12', 83, 'Accessories', True),
    ('Slim Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '46.90', 65, 'Accessories', True),
    ('Slim Power Bank', 'Practical accessory for everyday use with durable materials', '106.80', 43, 'Accessories', True),
    ('Slim Webcam', 'Practical accessory for everyday use with durable materials', '73.54', 137, 'Accessories', True),
    ('Slim USB-C Hub', 'Practical accessory for everyday use with durable materials', '10.69', 83, 'Accessories', True),
    ('Slim Phone Stand', 'Practical accessory for everyday use with durable materials', '140.89', 33, 'Accessories', True),
    ('Slim External SSD', 'Practical accessory for everyday use with durable materials', '35.54', 96, 'Accessories', True),
    ('Multiport USB-C Charger', 'Practical accessory for everyday use with durable materials', '52.83', 69, 'Accessories', True),
    ('Multiport Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '97.51', 69, 'Accessories', True),
    ('Multiport Wireless Mouse', 'Practical accessory for everyday use with durable materials', '118.53', 40, 'Accessories', True),
    ('Multiport Laptop Stand', 'Practical accessory for everyday use with durable materials', '74.41', 179, 'Accessories', False),
    ('Multiport Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '47.18', 85, 'Accessories', False),
    ('Multiport Power Bank', 'Practical accessory for everyday use with durable materials', '114.35', 80, 'Accessories', False),
    ('Multiport Webcam', 'Practical accessory for everyday use with durable materials', '39.90', 70, 'Accessories', True),
    ('Multiport USB-C Hub', 'Practical accessory for everyday use with durable materials', '29.57', 105, 'Accessories', True),
    ('Multiport Phone Stand', 'Practical accessory for everyday use with durable materials', '25.95', 39, 'Accessories', True),
    ('Multiport External SSD', 'Practical accessory for everyday use with durable materials', '7.80', 153, 'Accessories', True),
    ('Rechargeable USB-C Charger', 'Practical accessory for everyday use with durable materials', '133.80', 115, 'Accessories', True),
    ('Rechargeable Braided USB-C Cable', 'Practical accessory for everyday use with durable materials', '22.93', 158, 'Accessories', True),
    ('Rechargeable Wireless Mouse', 'Practical accessory for everyday use with durable materials', '33.43', 168, 'Accessories', True),
    ('Rechargeable Laptop Stand', 'Practical accessory for everyday use with durable materials', '91.55', 91, 'Accessories', True),
    ('Rechargeable Bluetooth Speaker', 'Practical accessory for everyday use with durable materials', '88.52', 144, 'Accessories', False),
    ('Rechargeable Power Bank', 'Practical accessory for everyday use with durable materials', '33.05', 75, 'Accessories', True),
    ('Rechargeable Webcam', 'Practical accessory for everyday use with durable materials', '129.54', 45, 'Accessories', True),
    ('Rechargeable USB-C Hub', 'Practical accessory for everyday use with durable materials', '81.31', 60, 'Accessories', True),
    ('Rechargeable Phone Stand', 'Practical accessory for everyday use with durable materials', '130.58', 166, 'Accessories', True),
    ('Rechargeable External SSD', 'Practical accessory for everyday use with durable materials', '137.41', 161, 'Accessories', True),
    ('Classic Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '101.42', 89, 'Clothing', True),
    ('Classic Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '41.94', 82, 'Clothing', True),
    ('Classic Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '22.13', 45, 'Clothing', True),
    ('Classic Running Shorts', 'Comfortable everyday apparel designed for regular wear', '51.73', 162, 'Clothing', True),
    ('Classic Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '47.93', 76, 'Clothing', True),
    ('Classic Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '20.53', 17, 'Clothing', False),
    ('Classic Crew Socks', 'Comfortable everyday apparel designed for regular wear', '108.76', 98, 'Clothing', True),
    ('Classic Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '21.50', 109, 'Clothing', True),
    ('Classic Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '35.50', 68, 'Clothing', True),
    ('Everyday Cotton T-Shirt', 'Comfortable everyday apparel designed for regular wear', '85.77', 59, 'Clothing', True),
    ('Everyday Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '27.53', 60, 'Clothing', True),
    ('Everyday Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '77.62', 43, 'Clothing', True),
    ('Everyday Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '27.38', 46, 'Clothing', False),
    ('Everyday Running Shorts', 'Comfortable everyday apparel designed for regular wear', '80.07', 96, 'Clothing', True),
    ('Everyday Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '55.27', 134, 'Clothing', False),
    ('Everyday Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '97.52', 109, 'Clothing', True),
    ('Everyday Crew Socks', 'Comfortable everyday apparel designed for regular wear', '18.17', 147, 'Clothing', True),
    ('Everyday Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '86.03', 171, 'Clothing', True),
    ('Everyday Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '116.10', 109, 'Clothing', True),
    ('Lightweight Cotton T-Shirt', 'Comfortable everyday apparel designed for regular wear', '76.95', 96, 'Clothing', True),
    ('Lightweight Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '79.61', 116, 'Clothing', True),
    ('Lightweight Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '6.71', 10, 'Clothing', True),
    ('Lightweight Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '6.81', 68, 'Clothing', True),
    ('Lightweight Running Shorts', 'Comfortable everyday apparel designed for regular wear', '82.79', 121, 'Clothing', True),
    ('Lightweight Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '52.34', 147, 'Clothing', True),
    ('Lightweight Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '20.56', 178, 'Clothing', True),
    ('Lightweight Crew Socks', 'Comfortable everyday apparel designed for regular wear', '13.58', 22, 'Clothing', True),
    ('Lightweight Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '46.39', 128, 'Clothing', True),
    ('Lightweight Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '64.67', 83, 'Clothing', True),
    ('Relaxed-Fit Cotton T-Shirt', 'Comfortable everyday apparel designed for regular wear', '115.38', 170, 'Clothing', True),
    ('Relaxed-Fit Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '25.90', 15, 'Clothing', True),
    ('Relaxed-Fit Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '66.84', 68, 'Clothing', True),
    ('Relaxed-Fit Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '79.61', 52, 'Clothing', True),
    ('Relaxed-Fit Running Shorts', 'Comfortable everyday apparel designed for regular wear', '106.77', 118, 'Clothing', False),
    ('Relaxed-Fit Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '111.17', 95, 'Clothing', True),
    ('Relaxed-Fit Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '15.48', 131, 'Clothing', True),
    ('Relaxed-Fit Crew Socks', 'Comfortable everyday apparel designed for regular wear', '40.46', 176, 'Clothing', True),
    ('Relaxed-Fit Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '26.49', 175, 'Clothing', True),
    ('Relaxed-Fit Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '64.49', 39, 'Clothing', True),
    ('Slim-Fit Cotton T-Shirt', 'Comfortable everyday apparel designed for regular wear', '83.88', 58, 'Clothing', True),
    ('Slim-Fit Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '95.89', 153, 'Clothing', False),
    ('Slim-Fit Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '98.31', 51, 'Clothing', True),
    ('Slim-Fit Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '119.63', 44, 'Clothing', True),
    ('Slim-Fit Running Shorts', 'Comfortable everyday apparel designed for regular wear', '112.87', 171, 'Clothing', True),
    ('Slim-Fit Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '118.84', 56, 'Clothing', True),
    ('Slim-Fit Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '46.36', 132, 'Clothing', True),
    ('Slim-Fit Crew Socks', 'Comfortable everyday apparel designed for regular wear', '38.05', 118, 'Clothing', False),
    ('Slim-Fit Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '26.09', 179, 'Clothing', True),
    ('Slim-Fit Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '76.18', 114, 'Clothing', True),
    ('Quick-Dry Cotton T-Shirt', 'Comfortable everyday apparel designed for regular wear', '114.91', 124, 'Clothing', True),
    ('Quick-Dry Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '20.92', 173, 'Clothing', True),
    ('Quick-Dry Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '96.80', 121, 'Clothing', True),
    ('Quick-Dry Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '54.82', 131, 'Clothing', True),
    ('Quick-Dry Running Shorts', 'Comfortable everyday apparel designed for regular wear', '49.51', 95, 'Clothing', True),
    ('Quick-Dry Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '8.82', 80, 'Clothing', True),
    ('Quick-Dry Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '52.39', 57, 'Clothing', True),
    ('Quick-Dry Crew Socks', 'Comfortable everyday apparel designed for regular wear', '86.75', 118, 'Clothing', True),
    ('Quick-Dry Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '45.55', 171, 'Clothing', True),
    ('Quick-Dry Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '110.74', 19, 'Clothing', True),
    ('Soft Cotton Cotton T-Shirt', 'Comfortable everyday apparel designed for regular wear', '42.30', 68, 'Clothing', True),
    ('Soft Cotton Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '94.27', 149, 'Clothing', True),
    ('Soft Cotton Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '15.72', 80, 'Clothing', True),
    ('Soft Cotton Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '109.86', 33, 'Clothing', False),
    ('Soft Cotton Running Shorts', 'Comfortable everyday apparel designed for regular wear', '67.56', 153, 'Clothing', True),
    ('Soft Cotton Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '118.52', 49, 'Clothing', True),
    ('Soft Cotton Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '19.62', 159, 'Clothing', True),
    ('Soft Cotton Crew Socks', 'Comfortable everyday apparel designed for regular wear', '22.75', 150, 'Clothing', False),
    ('Soft Cotton Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '41.10', 135, 'Clothing', True),
    ('Soft Cotton Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '54.60', 10, 'Clothing', True),
    ('Outdoor Cotton T-Shirt', 'Comfortable everyday apparel designed for regular wear', '15.14', 73, 'Clothing', True),
    ('Outdoor Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '73.68', 161, 'Clothing', True),
    ('Outdoor Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '43.73', 71, 'Clothing', True),
    ('Outdoor Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '112.04', 31, 'Clothing', True),
    ('Outdoor Running Shorts', 'Comfortable everyday apparel designed for regular wear', '27.43', 100, 'Clothing', True),
    ('Outdoor Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '78.57', 27, 'Clothing', True),
    ('Outdoor Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '84.26', 150, 'Clothing', False),
    ('Outdoor Crew Socks', 'Comfortable everyday apparel designed for regular wear', '80.77', 172, 'Clothing', True),
    ('Outdoor Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '70.34', 76, 'Clothing', True),
    ('Outdoor Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '5.66', 104, 'Clothing', True),
    ('Essential Cotton T-Shirt', 'Comfortable everyday apparel designed for regular wear', '57.00', 7, 'Clothing', False),
    ('Essential Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '93.89', 60, 'Clothing', True),
    ('Essential Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '32.49', 106, 'Clothing', False),
    ('Essential Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '66.22', 44, 'Clothing', True),
    ('Essential Running Shorts', 'Comfortable everyday apparel designed for regular wear', '11.16', 171, 'Clothing', True),
    ('Essential Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '102.93', 146, 'Clothing', True),
    ('Essential Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '110.68', 112, 'Clothing', True),
    ('Essential Crew Socks', 'Comfortable everyday apparel designed for regular wear', '31.05', 150, 'Clothing', True),
    ('Essential Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '59.22', 48, 'Clothing', True),
    ('Essential Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '86.32', 116, 'Clothing', True),
    ('Performance Cotton T-Shirt', 'Comfortable everyday apparel designed for regular wear', '53.88', 12, 'Clothing', True),
    ('Performance Oxford Shirt', 'Comfortable everyday apparel designed for regular wear', '112.15', 111, 'Clothing', True),
    ('Performance Zip Hoodie', 'Comfortable everyday apparel designed for regular wear', '35.78', 96, 'Clothing', True),
    ('Performance Denim Jeans', 'Comfortable everyday apparel designed for regular wear', '31.96', 8, 'Clothing', True),
    ('Performance Running Shorts', 'Comfortable everyday apparel designed for regular wear', '41.18', 108, 'Clothing', True),
    ('Performance Rain Jacket', 'Comfortable everyday apparel designed for regular wear', '24.73', 150, 'Clothing', True),
    ('Performance Canvas Sneakers', 'Comfortable everyday apparel designed for regular wear', '104.09', 54, 'Clothing', True),
    ('Performance Crew Socks', 'Comfortable everyday apparel designed for regular wear', '69.61', 61, 'Clothing', True),
    ('Performance Baseball Cap', 'Comfortable everyday apparel designed for regular wear', '116.88', 125, 'Clothing', True),
    ('Performance Sports Leggings', 'Comfortable everyday apparel designed for regular wear', '6.74', 18, 'Clothing', True),
    ('Modern Dinner Plate Set', 'Useful household item designed for daily home use', '133.53', 165, 'Home', True),
    ('Modern Food Storage Set', 'Useful household item designed for daily home use', '64.58', 50, 'Home', False),
    ('Modern Frying Pan', 'Useful household item designed for daily home use', '176.32', 72, 'Home', True),
    ('Modern Water Bottle', 'Useful household item designed for daily home use', '82.38', 19, 'Home', True),
    ('Modern Bath Towel', 'Useful household item designed for daily home use', '68.52', 115, 'Home', True),
    ('Modern LED Desk Lamp', 'Useful household item designed for daily home use', '27.96', 24, 'Home', True),
    ('Modern Pillow', 'Useful household item designed for daily home use', '70.49', 87, 'Home', True),
    ('Modern Laundry Basket', 'Useful household item designed for daily home use', '33.58', 29, 'Home', True),
    ('Modern Wall Clock', 'Useful household item designed for daily home use', '73.20', 176, 'Home', True),
    ('Modern Ceramic Planter', 'Useful household item designed for daily home use', '45.42', 111, 'Home', True),
    ('Classic Dinner Plate Set', 'Useful household item designed for daily home use', '15.03', 18, 'Home', True),
    ('Classic Food Storage Set', 'Useful household item designed for daily home use', '108.27', 166, 'Home', True),
    ('Classic Frying Pan', 'Useful household item designed for daily home use', '115.79', 173, 'Home', True),
    ('Classic Water Bottle', 'Useful household item designed for daily home use', '20.61', 112, 'Home', True),
    ('Classic Bath Towel', 'Useful household item designed for daily home use', '19.13', 50, 'Home', True),
    ('Classic LED Desk Lamp', 'Useful household item designed for daily home use', '113.70', 45, 'Home', True),
    ('Classic Pillow', 'Useful household item designed for daily home use', '171.66', 136, 'Home', True),
    ('Classic Laundry Basket', 'Useful household item designed for daily home use', '132.99', 86, 'Home', True),
    ('Classic Wall Clock', 'Useful household item designed for daily home use', '50.77', 142, 'Home', True),
    ('Classic Ceramic Planter', 'Useful household item designed for daily home use', '7.67', 171, 'Home', True),
    ('Compact Dinner Plate Set', 'Useful household item designed for daily home use', '160.57', 174, 'Home', True),
    ('Compact Food Storage Set', 'Useful household item designed for daily home use', '89.86', 118, 'Home', False),
    ('Compact Frying Pan', 'Useful household item designed for daily home use', '108.60', 175, 'Home', True),
    ('Compact Water Bottle', 'Useful household item designed for daily home use', '127.88', 19, 'Home', True),
    ('Compact Bath Towel', 'Useful household item designed for daily home use', '164.80', 142, 'Home', True),
    ('Compact LED Desk Lamp', 'Useful household item designed for daily home use', '174.85', 155, 'Home', True),
    ('Compact Pillow', 'Useful household item designed for daily home use', '70.82', 48, 'Home', True),
    ('Compact Laundry Basket', 'Useful household item designed for daily home use', '116.00', 132, 'Home', True),
    ('Compact Wall Clock', 'Useful household item designed for daily home use', '100.34', 89, 'Home', True),
    ('Compact Ceramic Planter', 'Useful household item designed for daily home use', '116.27', 143, 'Home', True),
    ('Large Dinner Plate Set', 'Useful household item designed for daily home use', '112.51', 36, 'Home', True),
    ('Large Food Storage Set', 'Useful household item designed for daily home use', '130.90', 105, 'Home', True),
    ('Large Frying Pan', 'Useful household item designed for daily home use', '74.07', 101, 'Home', True),
    ('Large Water Bottle', 'Useful household item designed for daily home use', '100.44', 78, 'Home', True),
    ('Large Bath Towel', 'Useful household item designed for daily home use', '152.19', 17, 'Home', True),
    ('Large LED Desk Lamp', 'Useful household item designed for daily home use', '178.12', 120, 'Home', True),
    ('Large Pillow', 'Useful household item designed for daily home use', '82.28', 160, 'Home', True),
    ('Large Laundry Basket', 'Useful household item designed for daily home use', '61.04', 126, 'Home', True),
    ('Large Wall Clock', 'Useful household item designed for daily home use', '12.08', 108, 'Home', True),
    ('Large Ceramic Planter', 'Useful household item designed for daily home use', '159.67', 80, 'Home', True),
    ('Everyday Dinner Plate Set', 'Useful household item designed for daily home use', '50.27', 91, 'Home', True),
    ('Everyday Food Storage Set', 'Useful household item designed for daily home use', '154.43', 149, 'Home', True),
    ('Everyday Frying Pan', 'Useful household item designed for daily home use', '103.75', 134, 'Home', True),
    ('Everyday Water Bottle', 'Useful household item designed for daily home use', '177.72', 137, 'Home', True),
    ('Everyday Bath Towel', 'Useful household item designed for daily home use', '158.99', 125, 'Home', True),
    ('Everyday LED Desk Lamp', 'Useful household item designed for daily home use', '63.42', 128, 'Home', True),
    ('Everyday Pillow', 'Useful household item designed for daily home use', '77.54', 26, 'Home', True),
    ('Everyday Laundry Basket', 'Useful household item designed for daily home use', '35.09', 138, 'Home', True),
    ('Everyday Wall Clock', 'Useful household item designed for daily home use', '7.51', 147, 'Home', True),
    ('Everyday Ceramic Planter', 'Useful household item designed for daily home use', '83.39', 51, 'Home', False),
    ('Insulated Dinner Plate Set', 'Useful household item designed for daily home use', '135.40', 90, 'Home', True),
    ('Insulated Food Storage Set', 'Useful household item designed for daily home use', '37.20', 69, 'Home', True),
    ('Insulated Frying Pan', 'Useful household item designed for daily home use', '100.79', 114, 'Home', True),
    ('Insulated Water Bottle', 'Useful household item designed for daily home use', '88.99', 72, 'Home', True),
    ('Insulated Bath Towel', 'Useful household item designed for daily home use', '114.27', 151, 'Home', True),
    ('Insulated LED Desk Lamp', 'Useful household item designed for daily home use', '84.89', 35, 'Home', True),
    ('Insulated Pillow', 'Useful household item designed for daily home use', '38.05', 74, 'Home', True),
    ('Insulated Laundry Basket', 'Useful household item designed for daily home use', '24.66', 91, 'Home', True),
    ('Insulated Wall Clock', 'Useful household item designed for daily home use', '66.57', 13, 'Home', True),
    ('Insulated Ceramic Planter', 'Useful household item designed for daily home use', '143.07', 28, 'Home', True),
    ('Stackable Dinner Plate Set', 'Useful household item designed for daily home use', '134.11', 34, 'Home', True),
]


def seed_products(session: Session) -> int:
    created = 0
    for name, description, price, stock, category, active in PRODUCTS:
        product = session.scalar(select(Product).where(Product.name == name))
        if product is None:
            product = Product(name=name)
            session.add(product)
            created += 1
        product.description, product.price = description, Decimal(price)
        product.stock_quantity, product.category, product.active = stock, category, active
    session.commit()
    return created
